apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccount: nginx
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          args:
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/default-backend
            - --configmap=$(POD_NAMESPACE)/nginx-ingress-controller-conf
            - --apiserver-host=$APISERVER_HOST
            - --kubeconfig=$KUBECONFIG
            - --default-ssl-certificate=$(POD_NAMESPACE)/ingress-certificate
            - --v=2
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 80
            - containerPort: 18080
            - containerPort: 443
          volumeMounts:
            - mountPath: $CERTIFICATE_MOUNT_PATH
              name: certs
              readOnly: true
            - mountPath: /var/lib/$INGRESS_HOST/
              name: ingresscert
              readOnly: true
      volumes:
      - hostPath:
          path: $CERTIFICATE_MOUNT_PATH
        name: certs
      - hostPath:
          path: /var/lib/$INGRESS_HOST/
        name: ingresscert
